defmodule AshStorage.Plug.DiskServeTest do
  use ExUnit.Case, async: true

  import Plug.Test

  alias AshStorage.Plug.DiskServe

  @root Path.join(
          System.tmp_dir!(),
          "ash_storage_disk_serve_test_#{System.unique_integer([:positive])}"
        )

  # Simulated extensionless storage key (as generated by AshStorage.generate_key/0)
  @hex_key "1e7df7229a9664e5e172b0351afeba090eaf26de"

  setup_all do
    File.mkdir_p!(@root)
    File.write!(Path.join(@root, "hello.txt"), "hello world")
    File.write!(Path.join(@root, @hex_key), "<svg/>")

    on_exit(fn -> File.rm_rf!(@root) end)
    :ok
  end

  defp call(path, opts \\ []) do
    plug_opts =
      DiskServe.init(Keyword.merge([root: @root], opts))

    conn(:get, path)
    |> DiskServe.call(plug_opts)
  end

  describe "serving files" do
    test "serves a file with correct content" do
      conn = call("/hello.txt")
      assert conn.status == 200
      assert conn.resp_body == "hello world"
      # Public (unsigned) serving is not forced to no-store (the signed-only hardening).
      refute Plug.Conn.get_resp_header(conn, "cache-control") == ["no-store, private"]
    end

    test "sets content-type from file extension" do
      conn = call("/hello.txt")
      [content_type] = Plug.Conn.get_resp_header(conn, "content-type")
      assert content_type =~ "text/plain"
    end

    test "serves file via key/filename path" do
      conn = call("/#{@hex_key}/image.svg")
      assert conn.status == 200
      assert conn.resp_body == "<svg/>"
    end

    test "sets content-type from display filename in key/filename path" do
      conn = call("/#{@hex_key}/image.svg")
      [content_type] = Plug.Conn.get_resp_header(conn, "content-type")
      assert content_type =~ "image/svg+xml"
    end

    test "returns 404 for missing files" do
      conn = call("/nonexistent.txt")
      assert conn.status == 404
    end

    test "returns 404 for empty path" do
      conn = call("/")
      assert conn.status == 404
    end

    test "returns 404 for keys that traverse outside the root" do
      # Plant a sentinel one level above the served root.
      outside = Path.join(Path.dirname(@root), "disk_serve_escaped.txt")
      File.write!(outside, "TOP SECRET")
      on_exit(fn -> File.rm_rf!(outside) end)

      for path <- ["/../disk_serve_escaped.txt", "/../../etc/passwd",
                   "/a/../../disk_serve_escaped.txt"] do
        conn = call(path)
        assert conn.status == 404
        refute conn.resp_body == "TOP SECRET"
      end
    end
  end

  describe "signed URLs" do
    @secret "test-secret-32bytes!!!!!!!!!!!!!!"

    test "rejects requests without token" do
      conn = call("/hello.txt", secret: @secret)
      assert conn.status == 403
    end

    test "rejects requests with invalid token" do
      conn =
        conn(:get, "/hello.txt?token=invalid&expires=#{System.system_time(:second) + 3600}")
        |> DiskServe.call(DiskServe.init(root: @root, secret: @secret))

      assert conn.status == 403
    end

    test "rejects expired tokens" do
      expired = System.system_time(:second) - 10
      token = AshStorage.Token.sign(@secret, "hello.txt", expired)

      conn =
        conn(:get, "/hello.txt?token=#{token}&expires=#{expired}")
        |> DiskServe.call(DiskServe.init(root: @root, secret: @secret))

      assert conn.status == 403
    end

    test "serves file with valid token" do
      expires = System.system_time(:second) + 3600
      token = AshStorage.Token.sign(@secret, "hello.txt", expires)

      conn =
        conn(:get, "/hello.txt?token=#{URI.encode_www_form(token)}&expires=#{expires}")
        |> Plug.Conn.fetch_query_params()
        |> DiskServe.call(DiskServe.init(root: @root, secret: @secret))

      assert conn.status == 200
      assert conn.resp_body == "hello world"
      # Signed (token-bearing) responses must not be cached by intermediaries.
      assert Plug.Conn.get_resp_header(conn, "cache-control") == ["no-store, private"]
    end

    test "serves file with valid token using key/filename path" do
      expires = System.system_time(:second) + 3600
      token = AshStorage.Token.sign(@secret, @hex_key, expires)

      conn =
        conn(
          :get,
          "/#{@hex_key}/image.svg?token=#{URI.encode_www_form(token)}&expires=#{expires}"
        )
        |> Plug.Conn.fetch_query_params()
        |> DiskServe.call(DiskServe.init(root: @root, secret: @secret))

      assert conn.status == 200
      assert conn.resp_body == "<svg/>"
      [content_type] = Plug.Conn.get_resp_header(conn, "content-type")
      assert content_type =~ "image/svg+xml"
    end

    test "rejects token signed with full key/filename path instead of storage key" do
      expires = System.system_time(:second) + 3600
      wrong_key = "#{@hex_key}/image.svg"
      token = AshStorage.Token.sign(@secret, wrong_key, expires)

      conn =
        conn(
          :get,
          "/#{@hex_key}/image.svg?token=#{URI.encode_www_form(token)}&expires=#{expires}"
        )
        |> Plug.Conn.fetch_query_params()
        |> DiskServe.call(DiskServe.init(root: @root, secret: @secret))

      assert conn.status == 403
    end
  end

  describe "content-disposition" do
    test "sets attachment disposition from query param" do
      conn =
        conn(:get, "/hello.txt?disposition=attachment")
        |> Plug.Conn.fetch_query_params()
        |> DiskServe.call(DiskServe.init(root: @root))

      assert conn.status == 200
      [disposition] = Plug.Conn.get_resp_header(conn, "content-disposition")
      assert disposition == "attachment"
    end

    test "sets attachment with filename from query param" do
      conn =
        conn(:get, "/hello.txt?disposition=attachment&filename=download.txt")
        |> Plug.Conn.fetch_query_params()
        |> DiskServe.call(DiskServe.init(root: @root))

      assert conn.status == 200
      [disposition] = Plug.Conn.get_resp_header(conn, "content-disposition")
      assert disposition == "attachment; filename=\"download.txt\""
    end
  end
end
